/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include"STD_TYPES.h"
#include"BIT_Manipulation.h"
#include"RCC_interface.h"
#include"GPIO_interface.h"
#include"PORT_interface.h"
#include"LED_interface.h"
#include"USART_interface.h"

int main(void)
{
     u8 Received_Data;

	  RCC_voidSysClkInit();
	  RCC_voidEnablePeripheralClk(RCC_AHB1,GPIOA);
	  RCC_voidEnablePeripheralClk(RCC_APB2,USART1);

	  PORT_voidInit();
	  USART1_voidInit();

	    LED_Object LED1={Source_Connection_type,GPIO_PORTA,GPIO_PIN0};
	    LED_Object LED2={Source_Connection_type,GPIO_PORTA,GPIO_PIN2};




	    USART1_voidSynchReceiveData(&Received_Data);

	    USART1_voidSendData('1');
	    USART1_voidSendData('2');
	    USART1_voidSendData('3');
	    USART1_voidSendData('4');



		while(1)
		{
            if(Received_Data=='1'){
			LED_Status(LED1,LED_ON);
            }
            else if(Received_Data=='2')
            {
			LED_Status(LED2,LED_ON);
            }
		}
}
