/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"STD_TYPES.h"
#include"BIT_Manipulation.h"
#include"RCC_interface.h"
#include"GPIO_interface.h"
#include"PORT_interface.h"
#include"SevenSeg_Interface.h"

void delay_ms(u8 Copy_u8Input);

int main(void)
{

	    RCC_voidSysClkInit();
	    RCC_voidEnablePerClk(RCC_AHB1,AHB1_GPIOA);

	    PORT_VoidInit();

	    Seven_Segment_Object SSD1={Common_Cathode_Mode,GPIO_u8PORTA,GPIO_u8PIN5,GPIO_u8PORTA,GPIO_u8PIN0};
	while(1)
	{
		SSD_Display_Number(SSD1,1);
		delay_ms(200);
		SSD_Display_Number(SSD1,5);
		delay_ms(200);
	   SSD_Display_Number(SSD1,9);
	   delay_ms(200);
	}
}

void delay_ms(u8 Copy_u8Input)
{
	for(int i = 0; i < 1000 * Copy_u8Input; i++)
	{
		asm("NOP");
	}
}
