/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"STD_TYPES.h"
#include"BIT_Manipulation.h"
#include"RCC_interface.h"
#include"GPIO_interface.h"
#include"PORT_interface.h"
#include"LED_interface.h"


int main(void)
{
	   RCC_voidSysClkInit();
	   RCC_voidEnablePerClk(RCC_AHB1,AHB1_GPIOA);
	   RCC_voidEnablePerClk(RCC_AHB1,AHB1_GPIOB);

	   PORT_VoidInit();


    u8 Local_u8Stat1;
    u8 Local_u8Stat2;

    LED_Object LED1={Source_Connection_type,GPIO_u8PORTA,GPIO_u8PIN0};
    LED_Object LED2={Source_Connection_type,GPIO_u8PORTA,GPIO_u8PIN1};

	while(1)
	{
		GPIO_u8ReadPinValue(GPIO_u8PORTB,GPIO_u8PIN0,&Local_u8Stat1);
		GPIO_u8ReadPinValue(GPIO_u8PORTB,GPIO_u8PIN1,&Local_u8Stat2);
		LED_Status(LED1,Local_u8Stat1);
		LED_Status(LED2,Local_u8Stat2);

	//	for(i=0;i<255;i++);

	}

}
